// LogIn / LogOut
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT = 'LOGOUT';

// Fetch movies
const REQUEST_MOVIES = 'REQUEST_MOVIES';
const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
const FAILURE_MOVIES = 'FAILURE_MOVIES';
const MOVIES_SELECTOR = 'MOVIES_SELECTOR';
const REQUEST_GENRES_BY_ID = 'REQUEST_GENRES_BY_ID';
const RECEIVE_GENRES_BY_ID = 'RECEIVE_GENRES_BY_ID';

// Fetch movie
const REQUEST_MOVIE = 'REQUEST_MOVIE';
const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
const FAILURE_MOVIE = 'FAILURE_MOVIE';

// Search
const UPD_SEARCH_FIELD = 'UPD_SEARCH_FIELD';

// Favorites
const REQUEST_FAV_MOVIES = 'REQUEST_FAV_MOVIES';
const RECEIVE_FAV_MOVIES = 'RECEIVE_FAV_MOVIES';
const FAILURE_FAV_MOVIES = 'FAILURE_FAV_MOVIES';
const ADD_FAV = 'ADD_FAV';
const REMOVE_FAV = 'REMOVE_FAV';

export {
  LOGIN_SUCCESS,
  LOGOUT,
  REQUEST_MOVIES,
  RECEIVE_MOVIES,
  FAILURE_MOVIES,
  REQUEST_MOVIE,
  RECEIVE_MOVIE,
  FAILURE_MOVIE,
  MOVIES_SELECTOR,
  REQUEST_GENRES_BY_ID,
  RECEIVE_GENRES_BY_ID,
  UPD_SEARCH_FIELD,
  ADD_FAV,
  REMOVE_FAV,
  REQUEST_FAV_MOVIES,
  RECEIVE_FAV_MOVIES,
  FAILURE_FAV_MOVIES,
};
