// Login
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Fetch movies
const REQUEST_MOVIES = 'REQUEST_MOVIES';
const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
const FAILURE_MOVIES = 'FAILURE_MOVIES';
const SELECT_GENRE = 'SELECT_GENRE';

export {
  LOGIN_SUCCESS,
  REQUEST_MOVIES,
  RECEIVE_MOVIES,
  FAILURE_MOVIES,
  SELECT_GENRE,
};
